language: cpp
os: linux

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo apt-get -qq install cmake
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

env: CMD=cppcheck

addons:
  apt:
    packages:
      - cppcheck

script:
  - tools/scripts/cppcheck.py

matrix:
  fast_finish: true

  include:
    - script:
        - python tools/scripts/build.py --backend=gles2
      env:
        - CMD=build
        - TYPE=release
        - BACKEND=gles2
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/build.py --backend=software
      env:
        - CMD=build
        - TYPE=release
        - BACKEND=software
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/build.py --backend=vulkan
      env:
        - CMD=build
        - TYPE=release
        - BACKEND=vulkan
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/build.py --debug --backend=gles2
      env:
        - CMD=build
        - TYPE=debug
        - BACKEND=gles2
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/build.py --debug --backend=software
      env:
        - CMD=build
        - TYPE=debug
        - BACKEND=software
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/build.py --debug --backend=vulkan
      env:
        - CMD=build
        - TYPE=debug
        - BACKEND=vulkan
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev

    - script:
        - python tools/scripts/unittest.py --debug --backend=gles2
      env:
        - CMD=unittest
        - BACKEND=gles2
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
      cache:
        directories:
          - tools/frameworks

    - script:
        - python tools/scripts/unittest.py --debug --backend=software
      env:
        - CMD=unittest
        - BACKEND=software
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
      cache:
        directories:
          - tools/frameworks

    - script:
        - python tools/scripts/unittest.py --debug --backend=vulkan
      env:
        - CMD=unittest
        - BACKEND=vulkan
      addons:
        apt:
          packages:
            - freeglut3-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
      cache:
        directories:
          - tools/frameworks
